Server:
  Port: 8080

Spring:
  datasource:
    url: 
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.diealect.MySQLDialect
    show-sql: true
  main:
    web-application-type: servlet